<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Lawhaa_Shipping_Method extends WC_Shipping_Method {
    public function __construct( $instance_id = 0 ) {
        $this->id                 = 'lawhaa_rules';
        $this->instance_id        = absint( $instance_id );
        $this->method_title       = __( 'Simple Smart Shipping', 'lawhaa-shipping-rules' );
        $this->method_description = __( 'Calculates local, fast, carrier, pickup, and heavy sink shipping from city, district, cart value, and weight.', 'lawhaa-shipping-rules' );
        $this->supports           = array( 'shipping-zones', 'instance-settings' );

        $this->init();
    }

    public function init() {
        $this->init_form_fields();
        $this->init_instance_form_fields();
        $this->init_settings();
        $this->init_instance_settings();

        $this->enabled = $this->get_instance_option( 'enabled', 'yes' );
        $this->title   = $this->get_instance_option( 'title', __( 'Simple Shipping', 'lawhaa-shipping-rules' ) );
        $this->debug   = 'yes' === $this->get_instance_option( 'debug', 'no' );

        add_action( 'woocommerce_update_options_shipping_' . $this->id, array( $this, 'process_admin_options' ) );
    }

    public function init_form_fields() {
        $this->form_fields = array();
    }

    public function init_instance_form_fields() {
        $this->instance_form_fields = array(
            'enabled' => array(
                'title'   => __( 'Enable/Disable', 'lawhaa-shipping-rules' ),
                'type'    => 'checkbox',
                'label'   => __( 'Enable Simple Smart Shipping for this shipping zone', 'lawhaa-shipping-rules' ),
                'default' => 'yes',
            ),
            'title' => array(
                'title'       => __( 'Method group title', 'lawhaa-shipping-rules' ),
                'type'        => 'text',
                'description' => __( 'Internal title for the shipping-zone method. Customer-facing rate titles are generated by the rules.', 'lawhaa-shipping-rules' ),
                'default'     => __( 'Simple Shipping', 'lawhaa-shipping-rules' ),
                'desc_tip'    => true,
            ),
            'debug' => array(
                'title'       => __( 'Debug mode', 'lawhaa-shipping-rules' ),
                'type'        => 'checkbox',
                'label'       => __( 'Add rule context as shipping-rate metadata for testing', 'lawhaa-shipping-rules' ),
                'default'     => 'no',
            ),
        );
    }

    public function calculate_shipping( $package = array() ) {
        if ( 'yes' !== $this->enabled ) {
            return;
        }

        $context = Lawhaa_Shipping_Rules::package_context( $package );
        $rates   = Lawhaa_Shipping_Rules::build_rates( $context );

        foreach ( $rates as $rate ) {
            $rate_id = $this->id . ':' . sanitize_key( $rate['code'] );
            $meta    = isset( $rate['meta'] ) && is_array( $rate['meta'] ) ? $rate['meta'] : array();

            if ( $this->debug ) {
                $meta[ __( 'Lawhaa group', 'lawhaa-shipping-rules' ) ]    = isset( $context['group'] ) ? esc_html( (string) $context['group'] ) : '';
                $meta[ __( 'Destination city', 'lawhaa-shipping-rules' ) ] = isset( $context['city'] ) ? esc_html( (string) $context['city'] ) : '';
                $meta[ __( 'Destination area', 'lawhaa-shipping-rules' ) ] = isset( $context['district'] ) ? esc_html( (string) $context['district'] ) : '';
                $meta[ __( 'Package weight', 'lawhaa-shipping-rules' ) ]   = isset( $context['weight_kg'] ) ? wc_format_decimal( $context['weight_kg'], 2 ) . ' kg' : '';
                $meta[ __( 'Package amount', 'lawhaa-shipping-rules' ) ]   = isset( $context['amount'] ) ? wc_price( $context['amount'] ) : '';
            }

            $this->add_rate(
                array(
                    'id'        => $rate_id,
                    'label'     => $rate['label'],
                    'cost'      => max( 0, (float) $rate['cost'] ),
                    'taxes'     => '',
                    'meta_data' => $meta,
                )
            );
        }
    }
}
